language: python
python:
  - "2.7"

os:
  - linux

install:
  - "pip install -r requirements.txt"
  - "pip install check-manifest"
script:
  - python setup.py clean
  - python setup.py build_ext --inplace
  - check-manifest -u -v
  - python test/run

after_success:
 - pip install pyflakes
 - pyflakes tasks/*.py | tee >(wc -l)
 - pyflakes test/*.py  | tee >(wc -l)

notifications:
  email:
    recipients:
      - eric@konklone.com
      - tauberer@govtrack.us
      - dwillis@gmail.com
    on_success: change
    on_failure: change
